#!/bin/bash

rm_if_exists(){
  if [ -f $1 ]; then
    rm $1
  fi
}

# Remove all symlinks created by the install script.
rm_if_exists ${HOME}/.bash_profile
rm_if_exists ${HOME}/.bashrc
rm_if_exists ${HOME}/.gitconfig
rm_if_exists ${HOME}/.gitignore-global
rm_if_exists ${HOME}/.npmrc
rm_if_exists ${HOME}/.vimrc
